### ISSUE TITLE
check_five

### ISSUE THREAD

**Issue by IanaKhitsko** [tiwatit/Renju#4]
https://github.com/tiwatit/Renju/blob/e38f0ff52c287bf6c459a8b8db4f37918df87bbb/test.py#L25C5-L25C15

what if the rules will be changes, and the count for win will be 7, not five? You will have to rewrite the function name. Introduce another name for the method and add const for 5.

**Comment by tiwatit** [comment]
Added a global const for better future updates called WIN_NUMBER.
Changed the function name to check_win_condition as its more suiting.
