### ISSUE TITLE
Return with conditions

### ISSUE THREAD

**Issue by IanaKhitsko** [tiwatit/Renju#5]
https://github.com/tiwatit/Renju/blob/e38f0ff52c287bf6c459a8b8db4f37918df87bbb/test.py#L29

Can we try to return like this? 

return (check_horizontal(board, row, col, player) >= 5) || 
          ( check_vertical(board, row, col, player) >= 5) ||
( check_diagonal(board, row, col, player) >= 5);

the calculation will stop on the first true condition

**Comment by tiwatit** [comment]
Rewrote the return condition in a more compact and better manner using python "or" operator
